[package]
name = "nested-partition-loader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = { path = "uefi-rs", features = [ "exts", "logger" ] }
uefi-services = { path = "uefi-rs/uefi-services" }

log = { version = "0.4.11", default-features = false }

[patch.crates-io]
uefi-macros = { path = "uefi-rs/uefi-macros" }
uefi = { path = "uefi-rs" }
